services:
  app:
    build:
      context: .
    image: invoiceninja/invoiceninja-debian:latest
    restart: unless-stopped
    volumes:
      - app_public_v2:/var/www/html/public
      - app_storage_v2:/var/www/html/storage
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - app_public_v2:/var/www/html/public:ro
      - app_storage_v2:/var/www/html/storage:ro
    depends_on:
      - app

  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data_v2:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data_v2:/data

volumes:
  app_public_v2:
    driver: local
  app_storage_v2:
    driver: local
  mysql_data_v2:
    driver: local
  redis_data_v2:
    driver: local
